import { AchievementBadge } from "./types";
import {
  Flame,
  Brain,
  Timer,
  Zap,
  Moon,
  Sun,
  Trophy,
  Crown,
  Gamepad2,
  Gem,
  Award,
  BookOpen,
  Sparkles,
  CloudSun,
  LayoutGrid,
  ShieldCheck,
  Target,
  Volume2,
  CalendarCheck,
  Compass,
  Palette,
  Crosshair,
} from "lucide-react";

export const INITIAL_ACHIEVEMENTS: AchievementBadge[] = [
  {
    id: "badge-demon-streak",
    code: "BADGE-001",
    title: "百连胜魔王",
    titleEn: "Demon Streak King",
    category: "streak",
    rarity: "legendary",
    description: "连续完成每日打卡复习达到 100 天，统治背单词异世界",
    unlockCondition: "连胜天数达到 100 天",
    currentProgress: 14,
    targetProgress: 100,
    unit: "天",
    unlocked: false,
    rewardGems: 1000,
    rewardXp: 5000,
    rewardTitle: "百连胜魔王",
    icon: Flame,
    iconBgColor: "from-amber-500 via-orange-500 to-red-600",
    pixelArtStyle: "border-amber-400 shadow-amber-500/50",
  },
  {
    id: "badge-midnight-owl",
    code: "BADGE-002",
    title: "夜猫子复习王",
    titleEn: "Midnight Reviewer",
    category: "memory",
    rarity: "epic",
    description: "在深夜 00:00 - 04:00 期间完成 50 次卡片复习战报",
    unlockCondition: "深夜复习次数达到 50 次",
    currentProgress: 32,
    targetProgress: 50,
    unit: "次",
    unlocked: false,
    rewardGems: 300,
    rewardXp: 1500,
    rewardTitle: "深夜脑力守夜人",
    icon: Moon,
    iconBgColor: "from-indigo-600 via-purple-600 to-pink-600",
    pixelArtStyle: "border-purple-400 shadow-purple-500/50",
  },
  {
    id: "badge-pomodoro-master",
    code: "BADGE-003",
    title: "专注番茄达人",
    titleEn: "Pomodoro Master",
    category: "focus",
    rarity: "rare",
    description: "通过桌面沉浸番茄钟累计专注学习超过 2,500 分钟",
    unlockCondition: "专注时间达到 2,500 分钟",
    currentProgress: 1850,
    targetProgress: 2500,
    unit: "分钟",
    unlocked: false,
    rewardGems: 250,
    rewardXp: 1200,
    rewardTitle: "心流掌控者",
    icon: Timer,
    iconBgColor: "from-sky-500 via-cyan-500 to-blue-600",
    pixelArtStyle: "border-sky-400 shadow-sky-500/50",
  },
  {
    id: "badge-card-reaper",
    code: "BADGE-004",
    title: "闪卡收割机",
    titleEn: "Card Reaper",
    category: "memory",
    rarity: "legendary",
    description: "在 Anki 工作台中累计复习卡片突破 10,000 张",
    unlockCondition: "累计复习 10,000 张卡片",
    currentProgress: 4280,
    targetProgress: 10000,
    unit: "张",
    unlocked: false,
    rewardGems: 800,
    rewardXp: 4000,
    rewardTitle: "记忆收割神",
    icon: Zap,
    iconBgColor: "from-amber-400 via-yellow-500 to-amber-600",
    pixelArtStyle: "border-amber-300 shadow-amber-400/50",
  },
  {
    id: "badge-anki-geek",
    code: "BADGE-005",
    title: "Anki 原生极客",
    titleEn: "Anki Mastermind",
    category: "special",
    rarity: "epic",
    description: "启用 JS 脚本沙箱模式渲染复杂日系/重型模板卡片 50 次",
    unlockCondition: "使用脚本模式复习 50 次",
    currentProgress: 50,
    targetProgress: 50,
    unit: "次",
    unlocked: true,
    unlockedAt: "2026-08-01",
    rewardGems: 500,
    rewardXp: 2000,
    rewardTitle: "脚本黑客",
    icon: Sparkles,
    iconBgColor: "from-emerald-500 via-teal-500 to-emerald-700",
    pixelArtStyle: "border-emerald-400 shadow-emerald-500/50",
    claimedReward: true,
  },
  {
    id: "badge-arcade-god",
    code: "BADGE-006",
    title: "街机碰一碰战神",
    titleEn: "Arcade Warlord",
    category: "fun",
    rarity: "epic",
    description: "在 Arcade 单词碰一碰对决模式中单局分数突破 2,000 分",
    unlockCondition: "单局得分突破 2,000 分",
    currentProgress: 2150,
    targetProgress: 2000,
    unit: "分",
    unlocked: true,
    unlockedAt: "2026-08-10",
    rewardGems: 400,
    rewardXp: 1800,
    rewardTitle: "ADHD 对决王者",
    icon: Gamepad2,
    iconBgColor: "from-rose-500 via-pink-500 to-red-600",
    pixelArtStyle: "border-rose-400 shadow-rose-500/50",
    claimedReward: false,
  },
  {
    id: "badge-early-bird",
    code: "BADGE-007",
    title: "破晓早起鸟",
    titleEn: "Early Bird Learner",
    category: "streak",
    rarity: "rare",
    description: "在早晨 06:00 前完成一轮早安复习打卡",
    unlockCondition: "早起打卡达到 10 天",
    currentProgress: 10,
    targetProgress: 10,
    unit: "天",
    unlocked: true,
    unlockedAt: "2026-08-05",
    rewardGems: 200,
    rewardXp: 1000,
    rewardTitle: "破晓之星",
    icon: Sun,
    iconBgColor: "from-amber-400 via-orange-400 to-yellow-500",
    pixelArtStyle: "border-yellow-300 shadow-yellow-400/50",
    claimedReward: true,
  },
  {
    id: "badge-gem-hoarder",
    code: "BADGE-008",
    title: "记忆水晶富豪",
    titleEn: "Gem Hoarder",
    category: "special",
    rarity: "legendary",
    description: "通过每日挑战与成就累积拥有 5,000 颗记忆宝石",
    unlockCondition: "拥有 5,000 宝石",
    currentProgress: 1280,
    targetProgress: 5000,
    unit: "💎",
    unlocked: false,
    rewardGems: 1000,
    rewardXp: 3000,
    rewardTitle: "宝石大富翁",
    icon: Gem,
    iconBgColor: "from-sky-400 via-indigo-500 to-purple-600",
    pixelArtStyle: "border-cyan-300 shadow-cyan-400/50",
  },
  {
    id: "badge-perfect-attendance",
    code: "BADGE-009",
    title: "全勤狂魔",
    titleEn: "Perfect Attendance",
    category: "streak",
    rarity: "epic",
    description: "连续 30 天无断签复习，获得完美月度打卡日历",
    unlockCondition: "连续打卡 30 天",
    currentProgress: 14,
    targetProgress: 30,
    unit: "天",
    unlocked: false,
    rewardGems: 450,
    rewardXp: 2200,
    rewardTitle: "坚毅笃行者",
    icon: CalendarCheck,
    iconBgColor: "from-emerald-400 via-teal-500 to-emerald-600",
    pixelArtStyle: "border-emerald-300 shadow-emerald-400/50",
  },
  {
    id: "badge-note-alchemist",
    code: "BADGE-010",
    title: "卡牌炼金术士",
    titleEn: "Note Alchemist",
    category: "memory",
    rarity: "rare",
    description: "在 Anki 编辑器中自建原创笔记超过 100 条",
    unlockCondition: "自建笔记达到 100 条",
    currentProgress: 42,
    targetProgress: 100,
    unit: "条",
    unlocked: false,
    rewardGems: 200,
    rewardXp: 1200,
    rewardTitle: "知识炼金师",
    icon: BookOpen,
    iconBgColor: "from-violet-500 via-purple-500 to-indigo-600",
    pixelArtStyle: "border-violet-400 shadow-violet-500/50",
  },
  {
    id: "badge-combo-crusher",
    code: "BADGE-011",
    title: "暴击连击手",
    titleEn: "Combo Crusher",
    category: "memory",
    rarity: "epic",
    description: "单次复习流程中连续 50 张卡片精准选择 Easy (4分)",
    unlockCondition: "连续 50 卡选择 Easy",
    currentProgress: 28,
    targetProgress: 50,
    unit: "连击",
    unlocked: false,
    rewardGems: 350,
    rewardXp: 1800,
    rewardTitle: "绝招过目不忘",
    icon: Crosshair,
    iconBgColor: "from-orange-500 via-red-500 to-rose-600",
    pixelArtStyle: "border-orange-400 shadow-orange-500/50",
  },
  {
    id: "badge-weather-scholar",
    code: "BADGE-012",
    title: "气象学者",
    titleEn: "Weather Scholar",
    category: "fun",
    rarity: "common",
    description: "使用 1:1 拟物气象与 3D 轨迹曲线卡片查看天气 20 次",
    unlockCondition: "查看气象卡 20 次",
    currentProgress: 20,
    targetProgress: 20,
    unit: "次",
    unlocked: true,
    unlockedAt: "2026-08-08",
    rewardGems: 100,
    rewardXp: 500,
    rewardTitle: "观云者",
    icon: CloudSun,
    iconBgColor: "from-sky-400 via-blue-500 to-teal-500",
    pixelArtStyle: "border-sky-300 shadow-sky-400/50",
    claimedReward: true,
  },
  {
    id: "badge-widget-craftsman",
    code: "BADGE-013",
    title: "桌面小组件专家",
    titleEn: "Widget Craftsman",
    category: "fun",
    rarity: "common",
    description: "在自定义桌面工作台中同时固定固定 5 个互动小组件",
    unlockCondition: "固定 5 个小组件",
    currentProgress: 3,
    targetProgress: 5,
    unit: "个",
    unlocked: false,
    rewardGems: 150,
    rewardXp: 600,
    rewardTitle: "工作台设计师",
    icon: LayoutGrid,
    iconBgColor: "from-amber-400 via-yellow-500 to-orange-500",
    pixelArtStyle: "border-amber-300 shadow-amber-400/50",
  },
  {
    id: "badge-pearl-league-champ",
    code: "BADGE-014",
    title: "珍珠联赛冠军",
    titleEn: "Pearl League Champ",
    category: "special",
    rarity: "mythic",
    description: "在每周多邻国式段位联赛结算中登顶第 1 名",
    unlockCondition: "联赛周结算登顶第 1 名",
    currentProgress: 1,
    targetProgress: 1,
    unit: "次",
    unlocked: true,
    unlockedAt: "2026-08-09",
    rewardGems: 1500,
    rewardXp: 6000,
    rewardTitle: "珍珠桂冠王者",
    icon: Crown,
    iconBgColor: "from-yellow-300 via-amber-400 to-amber-600",
    pixelArtStyle: "border-yellow-200 shadow-yellow-300/60 ring-2 ring-amber-300",
    claimedReward: false,
  },
  {
    id: "badge-relentless-fighter",
    code: "BADGE-015",
    title: "不屈斗士",
    titleEn: "Relentless Fighter",
    category: "memory",
    rarity: "epic",
    description: "将 100 张重度遗忘 (Lapse >= 3) 的遗忘卡攻克重新学会",
    unlockCondition: "攻克 100 张 Lapse 遗忘卡",
    currentProgress: 64,
    targetProgress: 100,
    unit: "张",
    unlocked: false,
    rewardGems: 400,
    rewardXp: 2000,
    rewardTitle: "顽强不屈",
    icon: ShieldCheck,
    iconBgColor: "from-red-500 via-rose-600 to-pink-700",
    pixelArtStyle: "border-rose-400 shadow-rose-500/50",
  },
  {
    id: "badge-phonetic-maestro",
    code: "BADGE-016",
    title: "音律记忆师",
    titleEn: "Phonetic Maestro",
    category: "memory",
    rarity: "common",
    description: "在复习与单词卡片中聆听标准真人发音达到 500 次",
    unlockCondition: "播放发音达到 500 次",
    currentProgress: 320,
    targetProgress: 500,
    unit: "次",
    unlocked: false,
    rewardGems: 120,
    rewardXp: 600,
    rewardTitle: "金耳朵",
    icon: Volume2,
    iconBgColor: "from-blue-400 via-indigo-500 to-purple-500",
    pixelArtStyle: "border-indigo-300 shadow-indigo-400/50",
  },
  {
    id: "badge-pixel-architect",
    code: "BADGE-017",
    title: "像素积木匠",
    titleEn: "Pixel Block Architect",
    category: "fun",
    rarity: "rare",
    description: "解锁像素风格定制化工作台并成功运行 7 天",
    unlockCondition: "像素模式运行 7 天",
    currentProgress: 7,
    targetProgress: 7,
    unit: "天",
    unlocked: true,
    unlockedAt: "2026-08-03",
    rewardGems: 250,
    rewardXp: 1000,
    rewardTitle: "像素风领主",
    icon: Target,
    iconBgColor: "from-teal-400 via-emerald-500 to-green-600",
    pixelArtStyle: "border-emerald-300 shadow-emerald-400/50",
    claimedReward: true,
  },
  {
    id: "badge-thousand-vocabs",
    code: "BADGE-018",
    title: "千词掌控者",
    titleEn: "Thousand Vocabs Owner",
    category: "memory",
    rarity: "legendary",
    description: "在 Anki 词库中掌控卡片数量累计超过 1,000 张",
    unlockCondition: "掌握卡片突破 1,000 张",
    currentProgress: 1000,
    targetProgress: 1000,
    unit: "张",
    unlocked: true,
    unlockedAt: "2026-08-11",
    rewardGems: 900,
    rewardXp: 4500,
    rewardTitle: "千词掌门人",
    icon: Brain,
    iconBgColor: "from-purple-500 via-pink-500 to-rose-600",
    pixelArtStyle: "border-purple-300 shadow-purple-400/50",
    claimedReward: false,
  },
  {
    id: "badge-review-overlord",
    code: "BADGE-019",
    title: "终极复习狂人",
    titleEn: "Review Overlord",
    category: "memory",
    rarity: "epic",
    description: "单日复习卡片刷题量突破 500 张极限记录",
    unlockCondition: "单日刷题量达到 500 张",
    currentProgress: 380,
    targetProgress: 500,
    unit: "张",
    unlocked: false,
    rewardGems: 500,
    rewardXp: 2500,
    rewardTitle: "刷题霸主",
    icon: Trophy,
    iconBgColor: "from-amber-500 via-orange-600 to-red-600",
    pixelArtStyle: "border-amber-400 shadow-amber-500/50",
  },
  {
    id: "badge-time-traveler",
    code: "BADGE-020",
    title: "时光旅行者",
    titleEn: "Time Traveler",
    category: "special",
    rarity: "common",
    description: "使用改期或排程功能灵活调整卡片到期日 30 次",
    unlockCondition: "调整卡片排程 30 次",
    currentProgress: 18,
    targetProgress: 30,
    unit: "次",
    unlocked: false,
    rewardGems: 120,
    rewardXp: 600,
    rewardTitle: "时间领主",
    icon: Compass,
    iconBgColor: "from-cyan-400 via-sky-500 to-indigo-500",
    pixelArtStyle: "border-sky-300 shadow-sky-400/50",
  },
  {
    id: "badge-theme-pioneer",
    code: "BADGE-021",
    title: "Reasonix 艺术先锋",
    titleEn: "Artistic Pioneer",
    category: "special",
    rarity: "rare",
    description: "尝试并体验 Reasonix 风格系统的全部 6 款艺术主题方向",
    unlockCondition: "体验全部 6 款艺术主题",
    currentProgress: 6,
    targetProgress: 6,
    unit: "款",
    unlocked: true,
    unlockedAt: "2026-08-02",
    rewardGems: 300,
    rewardXp: 1200,
    rewardTitle: "配色策展人",
    icon: Palette,
    iconBgColor: "from-fuchsia-500 via-purple-500 to-pink-500",
    pixelArtStyle: "border-fuchsia-400 shadow-fuchsia-500/50",
    claimedReward: true,
  },
  {
    id: "badge-grand-slam",
    code: "BADGE-022",
    title: "全能大满贯神话",
    titleEn: "Grand Slam Master",
    category: "special",
    rarity: "mythic",
    description: "解锁任意 15 枚高级成就勋章，登顶 Reasonix 殿堂级荣誉榜",
    unlockCondition: "解锁 15 枚勋章",
    currentProgress: 8,
    targetProgress: 15,
    unit: "枚",
    unlocked: false,
    rewardGems: 2000,
    rewardXp: 10000,
    rewardTitle: "终极造物主",
    icon: Award,
    iconBgColor: "from-yellow-300 via-amber-400 via-rose-500 to-purple-600",
    pixelArtStyle: "border-amber-200 shadow-amber-300/70 ring-2 ring-yellow-400 animate-pulse",
  },
];

const LOCAL_STORAGE_KEY = "ra.achievements.v1";

export function loadAchievementsFromStorage(): AchievementBadge[] {
  try {
    const raw = localStorage.getItem(LOCAL_STORAGE_KEY);
    if (!raw) return INITIAL_ACHIEVEMENTS;
    const parsed = JSON.parse(raw) as AchievementBadge[];
    if (!Array.isArray(parsed) || parsed.length === 0) return INITIAL_ACHIEVEMENTS;

    // Merge missing initial achievements if any
    return INITIAL_ACHIEVEMENTS.map((init) => {
      const found = parsed.find((p) => p.id === init.id);
      if (!found) return init;
      return {
        ...init,
        currentProgress: found.currentProgress ?? init.currentProgress,
        unlocked: found.unlocked ?? init.unlocked,
        unlockedAt: found.unlockedAt ?? init.unlockedAt,
        claimedReward: found.claimedReward ?? init.claimedReward,
      };
    });
  } catch (e) {
    console.error("Failed to load achievements", e);
    return INITIAL_ACHIEVEMENTS;
  }
}

export function saveAchievementsToStorage(badges: AchievementBadge[]) {
  try {
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(badges));
  } catch (e) {
    console.error("Failed to save achievements", e);
  }
}
